import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import DashboardWrapper from "@/app/dashboardWrapper";
import React from "react";

import {Nunito} from 'next/font/google'
import {NextFont} from "next/dist/compiled/@next/font";

const _Nunito:NextFont =  Nunito({
    subsets:["latin"],
    weight:'400'

});




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
      <DashboardWrapper>

        {children}

      </DashboardWrapper>

      </body>
    </html>
  );
}
